name: T-Display CI

on:
  push:
    paths:
      - 'target/esp32/boards/LILYGO_T-Display/**'
      - 'target/esp32/esp32.mk'
      - '.github/workflows/t-display.yml'
  pull_request:
    paths:
      - 'target/esp32/boards/LILYGO_T-Display/**'
      - 'target/esp32/esp32.mk'
      - '.github/workflows/t-display.yml'

jobs:
  build_t-display:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T-Display
      run: |
        cp config_T-Display config
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T-Display_firmware
        path: ./bin/esp32/LILYGO_T-Display/