name: T-SIM7000G CI

on:
  push:
    paths:
      - 'target/esp32/boards/LILYGO_T-SIM7000G/**'
      - 'target/esp32/esp32.mk'
      - '.github/workflows/t-sim7000g.yml'
  pull_request:
    paths:
      - 'target/esp32/boards/LILYGO_T-SIM7000G/**'
      - 'target/esp32/esp32.mk'
      - '.github/workflows/t-sim7000g.yml'

jobs:
  build_t-sim7000g:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T-SIM7000G
      run: |
        cp config_T-SIM7000G config
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T-SIM7000G_firmware
        path: ./bin/esp32/LILYGO_T-SIM7000G/