name: T5-4.7 PLUS CI

on:
  push:
    paths:
      - 'target/esp32s3/boards/LILYGO_T5-4.7-PLUS/**'
      - 'target/esp32s3/esp32s3.mk'
      - '.github/workflows/t5-4.7-plus.yml'
  pull_request:
    paths:
      - 'target/esp32s3/boards/LILYGO_T5-4.7-PLUS/**'
      - 'target/esp32s3/esp32s3.mk'
      - '.github/workflows/t5-4.7-plus.yml'

jobs:
  build_t5-47-plus:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T5-4.7 Plus
      run: |
        cp config_T5-4.7-Plus config
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T5-4.7-PLUS_firmware
        path: ./bin/esp32s3/LILYGO_T5-4.7-PLUS/